version: "3"

services:
  inferno:
    image: tacoma/deqm-test-client:0.2.0
    ports:
      - "4567:4567"
  cqf_ruler:
    image: tacoma/cqf-ruler-preloaded:0.1.6.no-vs
    ports:
      - "8080:8080"
  ndjson_server:
    image: nginx
    ports:
      - "7070:8080"
    volumes:
      - ./ndjson_server/chbp-bulk-data-stu3:/usr/share/nginx/html:rw
      - ./ndjson_server/nginx.conf:/etc/nginx/nginx.conf:rw
  keycloak:
    image: jboss/keycloak:7.0.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
  fhir-bulk-proxy:
    image: artifacts.mitre.org:8200/fhir-bulk-proxy-mitrecerts:0.1.0
    ports:
      - "5000:5000"
    # NOTE: disabling s3 for our testing purposes
    environment:
      PORT: 5000
      # BUCKET: fhir-bulk-out-bucket
      SUBMISSIONURL: http://cqf_ruler:8080/cqf-ruler-dstu3/fhir
      EXTERNALURL: http://fhir-bulk-proxy:5000
      # RESOURCEBASEURL: s3location
      # Region doesn't make a difference. S3 is region free but it's still required
      REGION: us-east-1
