version: "3"

services:
  inferno:
    image: tacoma/deqm-test-client:0.3.0
    ports:
      - "4567:4567"
  cqf_ruler:
    image: tacoma/cqf-ruler-preloaded:0.2.0.no-vs
    ports:
      - "8080:8080"
