version: "3"

services:
  inferno:
    image: cypress-inferno_ruby_server
    ports:
      - "4567:4567"
  cqf_ruler:
    image: contentgroup/cqf-ruler:connectathon22-preloaded
    ports:
      - "8080:8080"
  ndjson_server:
    image: nginx
    ports:
      - "7070:8080"
    volumes:
      - ./ndjson_server/chbp-bulk-data-stu3:/usr/share/nginx/html:rw
      - ./ndjson_server/nginx.conf:/etc/nginx/nginx.conf:rw
  keycloak:
    image: jboss/keycloak:7.0.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd